### ISSUE TITLE
Partial searches for channel not returning

### ISSUE THREAD

**Issue by affa85** [lbryio/lighthouse#51] opened 2018-03-12 15:37 UTC
Searching for the channelname wouldnt come up unless you used @ in your search. It also had to be an exact match to get results

**Comment by kauffj** [comment] 2018-03-12 16:16
@tiger5226 can you handle this?

**Comment by tzarebczan** [comment] 2018-03-13 01:37
To clarify, even typing the @ in front only works because its the exact URL, not that it returns in search results. I don't see any channels in my search tests.

**Comment by tzarebczan** [comment] 2018-03-14 23:47
@affa85 's channel name is "Thefrugalvegan". Unless you type in the entire term into search, you don't get any results.

**Comment by affa85** [comment] 2018-03-15 00:22
I just noticed if the channel has a capital letter in it, Like the 'T' Thefrugalvegan. If I try lowercase t, it won't show up in search

**Comment by tzarebczan** [comment] 2018-03-15 00:28
@affa85 comes up for me, are you sure you aren't clicking enter (this causes you to go to the exact claim).

**Comment by affa85** [comment] 2018-03-15 00:46
@tzarebczan yeah, i still think every search engine is google. Sorry. 

It still can't be a partial search. I.e "frugalvegan" instead of "thefrugalvegan"

**Comment by tiger5226** [comment] 2018-03-15 03:32
Thanks for reporting the issue! I found the root cause of this problem. It wasn't able to search to see if a string contained the search term, hence the full match only. 

`match` query for elastic search doesn't support wildcards like `query_string`. I have adjusted the query to take multiple search query types into account. 

Please see the PR referenced below for details and weights. 

Should be fixed by #54

**Comment by tiger5226** [comment] 2018-03-17 14:14
The latest deployment of lighthouse corrects this issue. The following searches now return the mentioned channel.

https://lighthouse.lbry.io/search?s=Thefrugalvegan
https://lighthouse.lbry.io/search?s=thefrugalvegan
https://lighthouse.lbry.io/search?s=thefrugalveg
https://lighthouse.lbry.io/search?s=frugalvegan

**Closed by tiger5226** 2018-03-17 14:14 UTC
