### ISSUE TITLE
poor search results on related content / related to weighing on claim bid and %20?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#108] opened 2018-08-27 17:54 UTC
When going to lbry://cz-abl-rhodes#4eff956d91e02c9baae3f1f843a01cadf08b7556, the recommended results are pretty poor (based on the title). Search query: https://lighthouse.lbry.io/search?s=CryptoCandor%20%7C%20Live%20w%20Crypto%20Zombie,%20Sara%20-%20Altcoin%20Buzz%20Ladies,%20&%20Rhode%20Block!&size=20&from=0

I'm guessing this is related to https://github.com/lbryio/lighthouse/issues/32

**Comment by tzarebczan** [comment] 2018-08-27 18:07
here's another example: https://www.screencast.com/t/Fe32DyMQPHS

**Comment by tzarebczan** [comment] 2018-08-27 18:34
Here's an even worse one...lots of the @Porn hits from the community top bids:
![image](https://user-images.githubusercontent.com/8120721/44678417-4d683200-aa06-11e8-9803-92291a50ea75.png)

**Comment by tzarebczan** [comment] 2018-08-27 20:52
Just noticed: https://github.com/lbryio/lbry-desktop/issues/1911 

so the query was: https://lighthouse.lbry.io/autocomplete?s=GameTales%20 - the %20 (space) is bringing in the porn results. Maybe this is what's causing it to happen on other queries too.

**Comment by tiger5226** [comment] 2018-08-27 21:54
@seanyesmunt created another issue for this. He is now filtering out NSFW content appside. #110 check it out. If we can avoid the unintended side effects of effective amount is that preferable? I mean what we have is what we expected by implementing the issue, just not desired.

**Comment by tiger5226** [comment] 2018-08-27 22:51
there should be no leading or trailing spaces in a search. We can trim both sides of any query that comes in to enforce that.

**Comment by tiger5226** [comment] 2018-08-27 22:52
I am also worried that we are doing something wrong app side to produce this. @seanyesmunt Any idea how a trailing space is getting passed to the search api?

**Comment by tzarebczan** [comment] 2018-08-28 04:05
It's not only an issue with the trailing space, it's an issue with any spaces. See first example: https://lighthouse.lbry.io/search?s=CryptoCandor%20%7C%20Live%20w%20Crypto%20Zombie,%20Sara%20-%20Altcoin%20Buzz%20Ladies,%20&%20Rhode%20Block!&size=20&from=0

**Comment by tzarebczan** [comment] 2018-08-28 13:37
If we don't understand how to handle this scenario, we should revert the effective amount changes for the time being.

**Comment by tzarebczan** [comment] 2018-08-28 22:13
Lighthouse IP was reverted to an earlier instance as a workaround.

**Comment by alyssaoc** [comment] 2018-08-29 13:38
Need to understand the root cause before proceeding

**Comment by tiger5226** [comment] 2018-09-16 01:56
The root cause was due to the search query not being trimmed. We previously had an issue with internal server errors on specific characters. These characters needed to be escaped. They also needed the trim function called. When I added this the results even with the effective amount worked great. 

@alyssaoc This needs coordination with @nikooo777 / @filipnyquist . They did something with the machine and reverted to an old vm? Not sure exactly what happened. The effective amount changes will cause internal server errors if the elasticsearch db is not rebuilt. The IP was changed, so I assume we can merge, pull, build, deploy on the REAL production instance, and then change the IPs back. 

@nikooo777 Can you please confirm?

Solved with https://github.com/lbryio/lighthouse/pull/114

**Comment by nikooo777** [comment] 2018-09-17 04:34
Correct!

@filipnyquist is this something you can handle in the following days? I can switch the IP whenever it's ready

**Comment by tiger5226** [comment] 2018-09-23 14:51
This has been merged. Currently awaiting a deployment to production for testing. Then if all goes well the ip can be switched to the production instance.

**Closed** 2018-09-23 21:54 UTC
Labels: needs: exploration, priority: medium, type: bug
