### ISSUE TITLE
cannot find claim with search terms from title

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#35] opened 2017-10-11 18:58 UTC
cannot get this claim to show in search results: lbry://tbg-48Bm1Nlos-E#6f8e02e095aa6bf17e1e511b164974ba087fece4 when searching for Marathon / Retro Games / Live Stream

**Comment by tiger5226** [comment] 2018-03-17 14:29
The following query returns it as the second result now.
https://lighthouse.lbry.io/search?s=Retro%20Games%20Marathon

Marathon is not a complete enough search term. There are too many results to show and it is not in the top 10 and the app only shows the top 10. Pagination would help here because it is in the results.
https://lighthouse.lbry.io/search?s=Marathon

Similarly Retro games is too common of a search phrase and it is not in the top 10 results. I confirmed it is there, just not top 10. Pagination would help. 
https://lighthouse.lbry.io/search?s=Retro%20Games

The same goes for Live Stream, it is just too common. 

We can close this now, because the latest deployment of Lighthouse does return it in results just not top 10 for all queries.

**Closed by tiger5226** 2018-03-17 14:29 UTC
