### ISSUE TITLE
"john cleese" search term does not return @JohnCleese channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#45] opened 2017-12-21 23:32 UTC
Looks like search has issues with multi term queries

**Comment by tiger5226** [comment] 2018-03-06 03:19
Hi Tom, 

I think I found the problem while looking into a different issue with lighthouse. In december

https://github.com/lbryio/lighthouse/commit/d285e4e4859fb7cf8cc45bb81848635691af3630

 the following was added 

https://github.com/lbryio/lighthouse/blob/master/server/controllers/lighthouse.js#L65

`phrase_prefix` is not good for multiple terms as a type for a `multi_match` query. The recommendation is `best_fields`. See docs below.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-best-fields

I am not an elastic search expert but since I found this I wanted to document it on the issue.

**Comment by tiger5226** [comment] 2018-03-06 04:24
Hi Tom, 

I was looking into the search behavior for ChainQuery and saw this and since I did the research I wanted to answer this one.

This is actually expected behavior. When a phrase is searched like "John Cleese" this gets interpreted as a  query for "(John) or (Cleese)". This means it is looking for the whole word "John" or the whole word "Cleese". If you want to search for words starting with "John" then you should enter "John*" as the search. This performs a search for terms prefixed with "John". Since the channel name is "JohnCleese" the whole word doesn't match either.

Now you could get more fancy and search for "John* AND *Cleese", this would look for terms prefixed with "John" and suffixed with "Cleese"

The bigger problem here is that lighthouse is not able to search titles or descriptions. It appears that it is only looking at the name field of a claim when searching ( which is what I was looking into ).

**Comment by tiger5226** [comment] 2018-03-10 02:04
@tzarebczan This should be resolved now with the recent deployment to production of lighthouse. "john cleese" now returns nothing but john cleese videos. Can this be closed now?

**Comment by filipnyquist** [comment] 2018-03-10 06:00
Yes, i recall this bug is fixed by the latest update!

**Closed by filipnyquist** 2018-03-10 06:00 UTC
Labels: type: bug
